export default {
    GITHUB_ACCOUNT_LOADED: 'GITHUB_ACCOUNT_LOADED',
    GITHUB_ACCOUNT_LOADING: 'GITHUB_ACCOUNT_LOADING',
    GITHUB_ACCOUNT_LOADING_FAILED: 'GITHUB_ACCOUNT_LOADING_FAILED',
    GITHUB_REPO_SELECTED: 'GITHUB_REPO_SELECTED',

    PRS_LOADED: 'PRS_LOADED',
    PRS_LOADING: 'PRS_LOADING',
    PRS_LOADING_FAILED: 'PRS_LOADING_FAILED',
}